version: '3.2'

services:
    mongodb:
        image: mongo
        restart: always
    redis:
        image: redis
        restart: always
    fiora:
        build: .
        restart: always
        ports:
            - '80:80'
        environment:
            - Database=mongodb://mongodb/xcn
            - RedisHost=redis
